export default [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      {
        internalType: 'address',
        name: '_associatedContract',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'associatedContract',
        type: 'address',
      },
    ],
    name: 'AssociatedContractUpdated',
    type: 'event',
    signature: '0x73f20cff579e8a4086fa607db83867595f1b6a798e718c0bfa0b94a404128e03',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'Staking',
    type: 'event',
    signature: '0xfba03de4f3817b65c8bbd83551b938ace8f4a72bfad6821d9b4088bd6a207980',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'Unstaking',
    type: 'event',
    signature: '0xfce1a9063ab422f6b95f8c9d5e2bee83ae07416cd5859af625809f3078f5d958',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: true,
    inputs: [],
    name: 'associatedContract',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xaefc4ccb',
  },
  {
    constant: true,
    inputs: [],
    name: 'getTokenCurrencyKeys',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x5b081237',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
      { internalType: 'address', name: '_account', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'refund',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x4020ed14',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'address',
        name: '_associatedContract',
        type: 'address',
      },
    ],
    name: 'setAssociatedContract',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x52f445ca',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
      {
        internalType: 'address',
        name: '_tokenAddress',
        type: 'address',
      },
      { internalType: 'uint8', name: '_decimals', type: 'uint8' },
    ],
    name: 'setTargetToken',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x3f6a1607',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
      { internalType: 'bool', name: '_activate', type: 'bool' },
    ],
    name: 'setTokenActivation',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x9d88955f',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
      { internalType: 'address', name: '_account', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'stake',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x8c610c8d',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    name: 'stakedAmountOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x480310bb',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'targetTokens',
    outputs: [
      {
        internalType: 'address',
        name: 'tokenAddress',
        type: 'address',
      },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'bool', name: 'activated', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x37092864',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
    ],
    name: 'tokenActivated',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8547dbd9',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
    ],
    name: 'tokenAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x97bb3ce9',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
    ],
    name: 'tokenDecimals',
    outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x44aedc5f',
  },
  {
    constant: true,
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'tokenList',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9ead7222',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'totalStakedAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2c20fce2',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'totalStakerCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x77e15451',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32',
        name: '_currencyKey',
        type: 'bytes32',
      },
      { internalType: 'address', name: '_account', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
    ],
    name: 'unstake',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xa98b9ff4',
  },
];
