const MAINNET_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0xb49f677943BC038e9857d61E7d053CaA2C1734C1',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'pEUR',
  },
  {
    feed: '0xBcE206caE7f0ec07b545EddE332A47C2F75bbeb3',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'pJPY',
  },
  {
    feed: '0x77F9710E7d0A19669A13c055F62cd80d313dF022',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'pAUD',
  },
  {
    feed: '0x5c0Ab2d9b5a7ed9f470386e82BB36A3613cDd4b5',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'pGBP',
  },
  {
    feed: '0x449d117117838fFA61263B61dA6301AA2a88B13A',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'pCHF',
  },
  {
    feed: '0x214eD9Da11D2fbe465a6fc601a91E62EbEc1a0D6',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'pXAU',
  },
  {
    feed: '0x379589227b15F1a12195D3f2d90bBc9F31f95235',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'pXAG',
  },
  {
    feed: '0xf3584F4dd3b467e73C2339EfD008665a70A4185c',
    asset: 'OIL',
    category: 'commodity',
    sign: '$',
    description: 'Perpetual Oil Futures',
    name: 'sOIL',
  },
  {
    feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'pBNB',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'pTRX',
  },
  {
    feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'pXTZ',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'pXRP',
  },
  {
    feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'pLTC',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'pLINK',
  },
  {
    feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'pEOS',
  },
  {
    feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'pETC',
  },
  {
    feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'sDASH',
  },
  {
    feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'sXMR',
  },
  {
    feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
  },
  {
    feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
    asset: 'AAVE',
    category: 'crypto',
    sign: '',
    description: 'Aave',
    name: 'sAAVE',
  },
  {
    feed: '0x553303d460EE0afB37EdFf9bE42922D8FF63220e',
    asset: 'UNI',
    category: 'crypto',
    sign: '',
    description: 'Uniswap',
    name: 'sUNI',
  },
  {
    feed: '0xA027702dbb89fbd58938e4324ac03B58d812b0E1',
    asset: 'YFI',
    category: 'crypto',
    sign: '',
    description: 'yearn.finance',
    name: 'sYFI',
  },
  {
    feed: '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734',
    asset: 'DOT',
    category: 'crypto',
    sign: '',
    description: 'Polkadot',
    name: 'sDOT',
  },
  {
    feed: '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01',
    asset: 'REN',
    category: 'crypto',
    sign: '',
    description: 'Ren',
    name: 'sREN',
  },
  {
    feed: '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5',
    asset: 'COMP',
    category: 'crypto',
    sign: '',
    description: 'Compound',
    name: 'sCOMP',
  },
  {
    feed: '0xE23FA0e8dd05D6f66a6e8c98cab2d9AE82A7550c',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    description: 'FTSE 100 Index',
    name: 'sFTSE',
  },
  {
    feed: '0x5c4939a2ab3A2a9f93A518d81d4f8D0Bc6a68980',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    description: 'Nikkei 225 Index',
    name: 'sNIKKEI',
  },
  {
    feed: '0x1ceDaaB50936881B3e449e47e40A2cDAF5576A4a',
    asset: 'TSLA',
    category: 'equities',
    sign: '',
    exchange: 'NASDAQ',
    description: 'Tesla',
    name: 'pTSLA',
  },
  {
    feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'pCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'pDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 1.55,
        weight: 5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.54,
        weight: 10,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        units: 4.72,
        weight: 15,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 26.06,
        weight: 5,
      },
      { asset: 'SNX', units: 87.2, weight: 15 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 680.59,
        weight: 5,
      },
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 100.71,
        weight: 15,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 334.06,
        weight: 5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 254.94,
        weight: 5,
      },
      {
        asset: 'SUSHI',
        category: 'crypto',
        sign: '',
        description: 'SushiSwap',
        units: 43.111,
        weight: 5,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.01604,
        weight: 5,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 14.84,
        weight: 5,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 90.661,
        weight: 2.5,
      },
      {
        asset: '1INCH',
        category: 'crypto',
        sign: '',
        description: '1inch',
        units: 71.837,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 40378, upperLimit: 60567, lowerLimit: 20189 },
  },
  {
    feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 1548, upperLimit: 2322, lowerLimit: 774 },
  },
  {
    feed: '0x14e613AC84a31f709eadbdF89C6CC390fDc9540A',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 253, upperLimit: 379.5, lowerLimit: 126.5 },
  },
  {
    feed: '0xacD0D1A29759CC01E8D925371B72cb2b5610EA25',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.0454, upperLimit: 0.0681, lowerLimit: 0.0227 },
  },
  {
    feed: '0x5239a625dEb44bF3EeAc2CD5366ba24b8e9DB63F',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 3.73, upperLimit: 5.595, lowerLimit: 1.865 },
  },
  {
    feed: '0xCed2660c6Dd1Ffd856A5A82C67f3482d88C50b12',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.4824, upperLimit: 0.7236, lowerLimit: 0.2412 },
  },
  {
    feed: '0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 28.15, upperLimit: 42.225, lowerLimit: 14.075 },
  },
  {
    feed: '0x6AF09DF7563C363B5763b9102712EbeD3b9e859B',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 179.5, upperLimit: 269.25, lowerLimit: 89.75 },
  },
  {
    feed: '0x10a43289895eAff840E8d45995BBa89f9115ECEe',
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4.06, upperLimit: 6.09, lowerLimit: 2.03 },
  },
  {
    feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2',
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 11.46, upperLimit: 17.19, lowerLimit: 5.73 },
  },
  {
    feed: '0xFb0cADFEa136E9E343cfb55B863a6Df8348ab912',
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 241.5, upperLimit: 362.25, lowerLimit: 120.75 },
  },
  {
    feed: '0xFA66458Cce7Dd15D8650015c4fce4D278271618F',
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 222.906, upperLimit: 334.36, lowerLimit: 111.453 },
  },
  {
    feed: '0xAE48c91dF1fE419994FFDa27da09D5aC69c30f55',
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.977, upperLimit: 1.466, lowerLimit: 0.489 },
  },
  {
    feed: '0x283D433435cFCAbf00263beEF6A362b7cc5ed9f2',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4946, upperLimit: 7419, lowerLimit: 2437 },
  },
  {
    feed: '0xa8E875F94138B0C5b51d1e1d5dE35bbDdd28EA87',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 1.55,
        weight: 5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.54,
        weight: 10,
      },
      {
        asset: 'AAVE',
        category: 'crypto',
        sign: '',
        description: 'Aave',
        units: 4.72,
        weight: 15,
      },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 26.06,
        weight: 5,
      },
      { asset: 'SNX', units: 87.2, weight: 15 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 680.59,
        weight: 5,
      },
      {
        asset: 'UNI',
        category: 'crypto',
        sign: '',
        description: 'Uniswap',
        units: 100.71,
        weight: 15,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 334.06,
        weight: 5,
      },
      {
        asset: 'CRV',
        category: 'crypto',
        sign: '',
        description: 'Curve DAO Token',
        units: 254.94,
        weight: 5,
      },
      {
        asset: 'SUSHI',
        category: 'crypto',
        sign: '',
        description: 'SushiSwap',
        units: 43.111,
        weight: 5,
      },
      {
        asset: 'YFI',
        category: 'crypto',
        sign: '',
        description: 'yearn.finance',
        units: 0.01604,
        weight: 5,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 14.84,
        weight: 5,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 90.661,
        weight: 2.5,
      },
      {
        asset: '1INCH',
        category: 'crypto',
        sign: '',
        description: '1inch',
        units: 71.837,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 13382, upperLimit: 20073, lowerLimit: 6691 },
  },
  {
    feed: '0xf3584F4dd3b467e73C2339EfD008665a70A4185c',
    asset: 'OIL',
    category: 'commodity',
    sign: '$',
    description: 'Inverse Perpetual Oil Futures',
    name: 'iOIL',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 45.087, upperLimit: 67.63, lowerLimit: 22.543 },
  },
  {
    feed: '0x547a514d5e3769680Ce22B2361c10Ea13619e8a9',
    asset: 'AAVE',
    category: 'crypto',
    sign: '',
    description: 'Inverse Aave',
    name: 'iAAVE',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 406, upperLimit: 609, lowerLimit: 203 },
  },
  {
    feed: '0x553303d460EE0afB37EdFf9bE42922D8FF63220e',
    asset: 'UNI',
    category: 'crypto',
    sign: '',
    description: 'Inverse Uniswap',
    name: 'iUNI',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 25.382, upperLimit: 38.073, lowerLimit: 12.691 },
  },
  {
    feed: '0xA027702dbb89fbd58938e4324ac03B58d812b0E1',
    asset: 'YFI',
    category: 'crypto',
    sign: '',
    description: 'Inverse yearn.finance',
    name: 'iYFI',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 35368, upperLimit: 53052, lowerLimit: 17684 },
  },
  {
    feed: '0x1C07AFb8E2B827c5A4739C6d59Ae3A5035f28734',
    asset: 'DOT',
    category: 'crypto',
    sign: '',
    description: 'Inverse Polkadot',
    name: 'iDOT',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 34.618, upperLimit: 51.928, lowerLimit: 17.309 },
  },
  {
    feed: '0x0f59666EDE214281e956cb3b2D0d69415AfF4A01',
    asset: 'REN',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ren',
    name: 'iREN',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 1.26, upperLimit: 1.89, lowerLimit: 0.63 },
  },
  {
    feed: '0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5',
    asset: 'COMP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Compound',
    name: 'iCOMP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 393, upperLimit: 589.5, lowerLimit: 196.5 },
  },
];

const ROPSTEN_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
  },
  {
    feed: '0xa28a03a00cEFE08d68025044FEfaC221cBEe8a55',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'pEUR',
  },
  {
    feed: '0x795122664E4D4A3F7e66E8674953C97ADc60B17C',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'pJPY',
  },
  {
    feed: '0x1e5a19e9f382DD254D6983FF253A64F0bF15058a',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'pAUD',
  },
  {
    feed: '0xA8Ce4412fb92Fc5f6257197B229FE75A8c2e1E58',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'pGBP',
  },
  {
    feed: '0x0c1dB240827677264E89AA6c0CC35C78BcC45799',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'pCHF',
  },
  {
    feed: '0x09340fFCD275735C4Dfef24d21017d5B1cbd00fD',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'pXAU',
  },
  {
    feed: '0x6021C0Ab48dDA82a81F83276AF123e0bd89eDCF3',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'pXAG',
  },
  {
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: undefined,
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'pBNB',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'pTRX',
  },
  {
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'pXTZ',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'pXRP',
  },
  {
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'pLTC',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'pLINK',
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'pEOS',
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'sBCH',
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'pETC',
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'sDASH',
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'sXMR',
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
  },
  {
    feed: '0xcC3A7753ee8a5C5969b068ed35eb5110b0c611A7',
    asset: 'FTSE100',
    category: 'equities',
    sign: '',
    exchange: 'LSE',
    description: 'FTSE 100 Index',
    name: 'sFTSE',
  },
  {
    feed: '0x95579a8376FFd7d66acDC1EC9992B7feDcb65854',
    asset: 'NIKKEI225',
    category: 'equities',
    sign: '',
    exchange: 'TSE',
    description: 'Nikkei 225 Index',
    name: 'sNIKKEI',
  },
  {
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'pCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 17.88,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 153.85,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 20.51,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 32.52,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 59.82,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'pDEFI',
    index: [
      {
        asset: 'LINK',
        category: 'crypto',
        sign: '',
        description: 'Chainlink',
        units: 92.583,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.432,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 502.718,
      },
      { asset: 'SNX', units: 107.686 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 1222.393,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 2164.709,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 357.085,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 119.197,
      },
      { asset: 'MLN', units: 6.495 },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    feed: undefined,
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 314.54, upperLimit: 550.445, lowerLimit: 78.635 },
  },
  {
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.0299, upperLimit: 0.04485, lowerLimit: 0.01495 },
  },
  {
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4.1915, upperLimit: 6.28725, lowerLimit: 2.09575 },
  },
  {
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.3042, upperLimit: 0.4563, lowerLimit: 0.1521 },
  },
  {
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 19.54, upperLimit: 29.31, lowerLimit: 9.77 },
  },
  {
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 3.8502, upperLimit: 5.7753, lowerLimit: 1.9251 },
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Bitcoin Cash',
    name: 'iBCH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 314.4821,
      upperLimit: 471.72315,
      lowerLimit: 157.24105,
    },
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 6.16, upperLimit: 9.24, lowerLimit: 3.08 },
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 98.6231,
      upperLimit: 147.93465,
      lowerLimit: 49.31155,
    },
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 91.2236,
      upperLimit: 136.8354,
      lowerLimit: 45.6118,
    },
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.08, upperLimit: 0.12, lowerLimit: 0.04 },
  },
  {
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 17.88,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 153.85,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 20.51,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 32.52,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 59.82,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 943.4772,
      upperLimit: 1415.2158,
      lowerLimit: 471.7386,
    },
  },
  {
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'LINK',
        category: 'crypto',
        sign: '',
        description: 'Chainlink',
        units: 92.583,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.432,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 502.718,
      },
      { asset: 'SNX', units: 107.686 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 1222.393,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 2164.709,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 357.085,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 119.197,
      },
      { asset: 'MLN', units: 6.495 },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 4249.0685,
      upperLimit: 6373.60275,
      lowerLimit: 2124.53425,
    },
  },
];

const RINKEBY_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x78F9e60608bF48a1155b4B2A5e31F32318a1d85F',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'pEUR',
  },
  {
    feed: '0x3Ae2F46a2D84e3D5590ee6Ee5116B80caF77DeCA',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'pJPY',
  },
  {
    feed: '0x21c095d2aDa464A294956eA058077F14F66535af',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'pAUD',
  },
  {
    feed: '0x7B17A813eEC55515Fb8F49F2ef51502bC54DD40F',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'pGBP',
  },
  {
    feed: '0x5e601CF5EF284Bcd12decBDa189479413284E1d2',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'pCHF',
  },
  {
    feed: '0x81570059A0cb83888f1459Ec66Aad1Ac16730243',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'pXAU',
  },
  {
    feed: '0x9c1946428f4f159dB4889aA6B218833f467e1BfD',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'pXAG',
  },
  {
    feed: '0xECe365B379E1dD183B20fc5f022230C044d51404',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0xcf0f51ca2cDAecb464eeE4227f5295F2384F84ED',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'pBNB',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xb29f616a0d54FF292e997922fFf46012a63E2FAe',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'pTRX',
  },
  {
    feed: '0xf57FCa8B932c43dFe560d3274262b2597BCD2e5A',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'pXTZ',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xc3E76f41CAbA4aB38F00c7255d4df663DA02A024',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'pXRP',
  },
  {
    feed: '0x4d38a35C2D87976F334c2d2379b535F1D461D9B4',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'pLTC',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xd8bD0a1cB028a31AA859A21A3758685a95dE4623',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'pLINK',
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'pEOS',
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Bitcoin Cash',
    name: 'sBCH',
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'pETC',
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Dash',
    name: 'sDASH',
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Monero',
    name: 'sXMR',
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Cardano',
    name: 'sADA',
  },
  {
    feed: '0x1a602D4928faF0A153A520f58B332f9CAFF320f7',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'pCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0x0630521aC362bc7A19a4eE44b57cE72Ea34AD01c',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'pDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      { asset: 'SNX', units: 82.84, weight: 10.2 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xECe365B379E1dD183B20fc5f022230C044d51404',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 314.54, upperLimit: 550.445, lowerLimit: 78.635 },
  },
  {
    feed: '0xcf0f51ca2cDAecb464eeE4227f5295F2384F84ED',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    feed: '0xb29f616a0d54FF292e997922fFf46012a63E2FAe',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.0299, upperLimit: 0.04485, lowerLimit: 0.01495 },
  },
  {
    feed: '0xf57FCa8B932c43dFe560d3274262b2597BCD2e5A',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4.1915, upperLimit: 6.28725, lowerLimit: 2.09575 },
  },
  {
    feed: '0xc3E76f41CAbA4aB38F00c7255d4df663DA02A024',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.3042, upperLimit: 0.4563, lowerLimit: 0.1521 },
  },
  {
    feed: '0xd8bD0a1cB028a31AA859A21A3758685a95dE4623',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 19.54, upperLimit: 29.31, lowerLimit: 9.77 },
  },
  {
    feed: '0x4d38a35C2D87976F334c2d2379b535F1D461D9B4',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 3.8502, upperLimit: 5.7753, lowerLimit: 1.9251 },
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Bitcoin Cash',
    name: 'iBCH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 314.4821,
      upperLimit: 471.72315,
      lowerLimit: 157.24105,
    },
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 6.16, upperLimit: 9.24, lowerLimit: 3.08 },
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 98.6231,
      upperLimit: 147.93465,
      lowerLimit: 49.31155,
    },
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 91.2236,
      upperLimit: 136.8354,
      lowerLimit: 45.6118,
    },
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.08, upperLimit: 0.12, lowerLimit: 0.04 },
  },
  {
    feed: '0x1a602D4928faF0A153A520f58B332f9CAFF320f7',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 943.4772,
      upperLimit: 1415.2158,
      lowerLimit: 471.7386,
    },
  },
  {
    feed: '0x0630521aC362bc7A19a4eE44b57cE72Ea34AD01c',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      { asset: 'SNX', units: 82.84, weight: 10.2 },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 4249.0685,
      upperLimit: 6373.60275,
      lowerLimit: 2124.53425,
    },
  },
];

const GOERLI_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
  },
  {
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
];

const KOVAN_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x6135b13325bfC4B00278B4abC5e20bbce2D6580e',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x9326BFA02ADD2366b30bacB125260Af641031331',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x6135b13325bfC4B00278B4abC5e20bbce2D6580e',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 15699, upperLimit: 27473.25, lowerLimit: 3924.75 },
  },
  {
    feed: '0x9326BFA02ADD2366b30bacB125260Af641031331',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 314.54, upperLimit: 550.445, lowerLimit: 78.635 },
  },
];

export default {
  1: MAINNET_PYNTHS,
  3: ROPSTEN_PYNTHS,
  4: RINKEBY_PYNTHS,
  5: GOERLI_PYNTHS,
  42: KOVAN_PYNTHS,
};
