const MAINNET_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
];

const ROPSTEN_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
  },
  {
    feed: '0xa28a03a00cEFE08d68025044FEfaC221cBEe8a55',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'pEUR',
  },
  {
    feed: '0x795122664E4D4A3F7e66E8674953C97ADc60B17C',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'pJPY',
  },
  {
    feed: '0x1e5a19e9f382DD254D6983FF253A64F0bF15058a',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'pAUD',
  },
  {
    feed: '0xA8Ce4412fb92Fc5f6257197B229FE75A8c2e1E58',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'pGBP',
  },
  {
    feed: '0x0c1dB240827677264E89AA6c0CC35C78BcC45799',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'pCHF',
  },
  {
    feed: '0x09340fFCD275735C4Dfef24d21017d5B1cbd00fD',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'pXAU',
  },
  {
    feed: '0x6021C0Ab48dDA82a81F83276AF123e0bd89eDCF3',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'pXAG',
  },
  {
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: undefined,
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'pBNB',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'pTRX',
  },
  {
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'pXTZ',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'pXRP',
  },
  {
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'pLTC',
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'pLINK',
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'pEOS',
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'pETC',
  },
  {
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'pCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 17.88,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 153.85,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 20.51,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 32.52,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 59.82,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'pDEFI',
    index: [
      {
        asset: 'LINK',
        category: 'crypto',
        sign: '',
        description: 'Chainlink',
        units: 92.583,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.432,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 502.718,
      },
      {
        asset: 'PERI',
        category: 'crypto',
        sign: '',
        description: 'Peri Finance Token',
        units: 107.686,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 1222.393,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 2164.709,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 357.085,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 119.197,
      },
      { asset: 'MLN', units: 6.495 },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    feed: undefined,
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 314.54, upperLimit: 550.445, lowerLimit: 78.635 },
  },
  {
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.0299, upperLimit: 0.04485, lowerLimit: 0.01495 },
  },
  {
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4.1915, upperLimit: 6.28725, lowerLimit: 2.09575 },
  },
  {
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.3042, upperLimit: 0.4563, lowerLimit: 0.1521 },
  },
  {
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 19.54, upperLimit: 29.31, lowerLimit: 9.77 },
  },
  {
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 3.8502, upperLimit: 5.7753, lowerLimit: 1.9251 },
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Bitcoin Cash',
    name: 'iBCH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 314.4821,
      upperLimit: 471.72315,
      lowerLimit: 157.24105,
    },
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 6.16, upperLimit: 9.24, lowerLimit: 3.08 },
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 98.6231,
      upperLimit: 147.93465,
      lowerLimit: 49.31155,
    },
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 91.2236,
      upperLimit: 136.8354,
      lowerLimit: 45.6118,
    },
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.08, upperLimit: 0.12, lowerLimit: 0.04 },
  },
  {
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 17.88,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 153.85,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 20.51,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 32.52,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 59.82,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 943.4772,
      upperLimit: 1415.2158,
      lowerLimit: 471.7386,
    },
  },
  {
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'LINK',
        category: 'crypto',
        sign: '',
        description: 'Chainlink',
        units: 92.583,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.432,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 502.718,
      },
      {
        asset: 'PERI',
        category: 'crypto',
        sign: '',
        description: 'Peri Finance Token',
        units: 107.686,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 1222.393,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 2164.709,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 357.085,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 119.197,
      },
      { asset: 'MLN', units: 6.495 },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 4249.0685,
      upperLimit: 6373.60275,
      lowerLimit: 2124.53425,
    },
  },
];

const RINKEBY_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x78F9e60608bF48a1155b4B2A5e31F32318a1d85F',
    asset: 'EUR',
    category: 'forex',
    sign: '€',
    description: 'Euros',
    name: 'pEUR',
  },
  {
    feed: '0x3Ae2F46a2D84e3D5590ee6Ee5116B80caF77DeCA',
    asset: 'JPY',
    category: 'forex',
    sign: '¥',
    description: 'Japanese Yen',
    name: 'pJPY',
  },
  {
    feed: '0x21c095d2aDa464A294956eA058077F14F66535af',
    asset: 'AUD',
    category: 'forex',
    sign: '$',
    description: 'Australian Dollars',
    name: 'pAUD',
  },
  {
    feed: '0x7B17A813eEC55515Fb8F49F2ef51502bC54DD40F',
    asset: 'GBP',
    category: 'forex',
    sign: '£',
    description: 'Pound Sterling',
    name: 'pGBP',
  },
  {
    feed: '0x5e601CF5EF284Bcd12decBDa189479413284E1d2',
    asset: 'CHF',
    category: 'forex',
    sign: 'Fr',
    description: 'Swiss Franc',
    name: 'pCHF',
  },
  {
    feed: '0x81570059A0cb83888f1459Ec66Aad1Ac16730243',
    asset: 'XAU',
    category: 'commodity',
    sign: 'oz',
    description: 'Gold Ounce',
    name: 'pXAU',
  },
  {
    feed: '0x9c1946428f4f159dB4889aA6B218833f467e1BfD',
    asset: 'XAG',
    category: 'commodity',
    sign: 'oz',
    description: 'Silver Ounce',
    name: 'pXAG',
  },
  {
    feed: '0xECe365B379E1dD183B20fc5f022230C044d51404',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Bitcoin',
    name: 'pBTC',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
  {
    feed: '0xcf0f51ca2cDAecb464eeE4227f5295F2384F84ED',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Binance Coin',
    name: 'pBNB',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xb29f616a0d54FF292e997922fFf46012a63E2FAe',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'TRON',
    name: 'pTRX',
  },
  {
    feed: '0xf57FCa8B932c43dFe560d3274262b2597BCD2e5A',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Tezos',
    name: 'pXTZ',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xc3E76f41CAbA4aB38F00c7255d4df663DA02A024',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Ripple',
    name: 'pXRP',
  },
  {
    feed: '0x4d38a35C2D87976F334c2d2379b535F1D461D9B4',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Litecoin',
    name: 'pLTC',
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xd8bD0a1cB028a31AA859A21A3758685a95dE4623',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Chainlink',
    name: 'pLINK',
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'EOS',
    name: 'pEOS',
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Ethereum Classic',
    name: 'pETC',
  },
  {
    feed: '0x1a602D4928faF0A153A520f58B332f9CAFF320f7',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Centralised Exchange Index',
    name: 'pCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0x0630521aC362bc7A19a4eE44b57cE72Ea34AD01c',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'DeFi Index',
    name: 'pDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'PERI',
        category: 'crypto',
        sign: '',
        description: 'Peri Finance Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
  },
  {
    feed: '0xECe365B379E1dD183B20fc5f022230C044d51404',
    asset: 'BTC',
    category: 'crypto',
    sign: '₿',
    description: 'Inverse Bitcoin',
    name: 'iBTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 10600, upperLimit: 15900, lowerLimit: 5300 },
  },
  {
    feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e',
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Inverse Ether',
    name: 'iETH',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 314.54, upperLimit: 550.445, lowerLimit: 78.635 },
  },
  {
    feed: '0xcf0f51ca2cDAecb464eeE4227f5295F2384F84ED',
    asset: 'BNB',
    category: 'crypto',
    sign: '',
    description: 'Inverse Binance Coin',
    name: 'iBNB',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 22.258, upperLimit: 33.387, lowerLimit: 11.129 },
  },
  {
    feed: '0xb29f616a0d54FF292e997922fFf46012a63E2FAe',
    asset: 'TRX',
    category: 'crypto',
    sign: '',
    description: 'Inverse TRON',
    name: 'iTRX',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.0299, upperLimit: 0.04485, lowerLimit: 0.01495 },
  },
  {
    feed: '0xf57FCa8B932c43dFe560d3274262b2597BCD2e5A',
    asset: 'XTZ',
    category: 'crypto',
    sign: '',
    description: 'Inverse Tezos',
    name: 'iXTZ',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 4.1915, upperLimit: 6.28725, lowerLimit: 2.09575 },
  },
  {
    feed: '0xc3E76f41CAbA4aB38F00c7255d4df663DA02A024',
    asset: 'XRP',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ripple',
    name: 'iXRP',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.3042, upperLimit: 0.4563, lowerLimit: 0.1521 },
  },
  {
    feed: '0xd8bD0a1cB028a31AA859A21A3758685a95dE4623',
    asset: 'LINK',
    category: 'crypto',
    sign: '',
    description: 'Inverse Chainlink',
    name: 'iLINK',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 19.54, upperLimit: 29.31, lowerLimit: 9.77 },
  },
  {
    feed: '0x4d38a35C2D87976F334c2d2379b535F1D461D9B4',
    asset: 'LTC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Litecoin',
    name: 'iLTC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 35.66, upperLimit: 53.49, lowerLimit: 17.83 },
  },
  {
    asset: 'EOS',
    category: 'crypto',
    sign: '',
    description: 'Inverse EOS',
    name: 'iEOS',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 3.8502, upperLimit: 5.7753, lowerLimit: 1.9251 },
  },
  {
    asset: 'BCH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Bitcoin Cash',
    name: 'iBCH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 314.4821,
      upperLimit: 471.72315,
      lowerLimit: 157.24105,
    },
  },
  {
    asset: 'ETC',
    category: 'crypto',
    sign: '',
    description: 'Inverse Ethereum Classic',
    name: 'iETC',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 6.16, upperLimit: 9.24, lowerLimit: 3.08 },
  },
  {
    asset: 'DASH',
    category: 'crypto',
    sign: '',
    description: 'Inverse Dash',
    name: 'iDASH',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 98.6231,
      upperLimit: 147.93465,
      lowerLimit: 49.31155,
    },
  },
  {
    asset: 'XMR',
    category: 'crypto',
    sign: '',
    description: 'Inverse Monero',
    name: 'iXMR',
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 91.2236,
      upperLimit: 136.8354,
      lowerLimit: 45.6118,
    },
  },
  {
    asset: 'ADA',
    category: 'crypto',
    sign: '',
    description: 'Inverse Cardano',
    name: 'iADA',
    subclass: 'PurgeablePynth',
    inverted: { entryPoint: 0.08, upperLimit: 0.12, lowerLimit: 0.04 },
  },
  {
    feed: '0x1a602D4928faF0A153A520f58B332f9CAFF320f7',
    asset: 'CEX',
    category: 'index',
    sign: '',
    description: 'Inverse Centralised Exchange Index',
    name: 'iCEX',
    index: [
      {
        asset: 'BNB',
        category: 'crypto',
        sign: '',
        description: 'Binance Coin',
        units: 12.88,
        weight: 29.15,
      },
      {
        asset: 'CRO',
        category: 'crypto',
        sign: '',
        description: 'Crypto com',
        units: 1303.31,
        weight: 24.3,
      },
      {
        asset: 'LEO',
        category: 'crypto',
        sign: '',
        description: 'UNUS SED LEO',
        units: 94.54,
        weight: 13.42,
      },
      {
        asset: 'HT',
        category: 'crypto',
        sign: '',
        description: 'Huobi Token',
        units: 23.06,
        weight: 11.73,
      },
      {
        asset: 'FTT',
        category: 'crypto',
        sign: '',
        description: 'FTX',
        units: 9.36,
        weight: 3.56,
      },
      {
        asset: 'OKB',
        category: 'crypto',
        sign: '',
        description: 'OKB',
        units: 25.72,
        weight: 16.97,
      },
      {
        asset: 'KCS',
        category: 'crypto',
        sign: '',
        description: 'KuCoin Shares',
        units: 9.18,
        weight: 0.87,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 943.4772,
      upperLimit: 1415.2158,
      lowerLimit: 471.7386,
    },
  },
  {
    feed: '0x0630521aC362bc7A19a4eE44b57cE72Ea34AD01c',
    asset: 'DEFI',
    category: 'index',
    sign: '',
    description: 'Inverse DeFi Index',
    name: 'iDEFI',
    index: [
      {
        asset: 'COMP',
        category: 'crypto',
        sign: '',
        description: 'Compound',
        units: 4.14,
        weight: 20.5,
      },
      {
        asset: 'MKR',
        category: 'crypto',
        sign: '',
        description: 'Maker',
        units: 0.74,
        weight: 15,
      },
      {
        asset: 'ZRX',
        category: 'crypto',
        sign: '',
        description: '0x',
        units: 668.16,
        weight: 9.7,
      },
      {
        asset: 'REP',
        category: 'crypto',
        sign: '',
        description: 'Augur',
        units: 9.52,
        weight: 7.2,
      },
      { asset: 'LEND', units: 581.76, weight: 6.7 },
      {
        asset: 'UMA',
        category: 'crypto',
        sign: '',
        description: 'UMA',
        units: 28.54,
        weight: 4.2,
      },
      {
        asset: 'PERI',
        category: 'crypto',
        sign: '',
        description: 'Peri Finance Token',
        units: 82.84,
        weight: 10.2,
      },
      {
        asset: 'REN',
        category: 'crypto',
        sign: '',
        description: 'Ren',
        units: 822.92,
        weight: 5,
      },
      {
        asset: 'LRC',
        category: 'crypto',
        sign: '',
        description: 'Loopring',
        units: 948.31,
        weight: 3.8,
      },
      {
        asset: 'KNC',
        category: 'crypto',
        sign: '',
        description: 'Kyber Network',
        units: 224.53,
        weight: 11.8,
      },
      {
        asset: 'BNT',
        category: 'crypto',
        sign: '',
        description: 'Bancor',
        units: 61.2,
        weight: 3.4,
      },
      {
        asset: 'BAL',
        category: 'crypto',
        sign: '',
        description: 'Balancer',
        units: 7.09,
        weight: 2.5,
      },
    ],
    subclass: 'PurgeablePynth',
    inverted: {
      entryPoint: 4249.0685,
      upperLimit: 6373.60275,
      lowerLimit: 2124.53425,
    },
  },
];

const GOERLI_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
  },
  {
    asset: 'ETH',
    category: 'crypto',
    sign: 'Ξ',
    description: 'Ether',
    name: 'pETH',
    subclass: 'MultiCollateralPynth',
  },
];

const KOVAN_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
];

const POLYGON_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
];

const MUMBAI_PYNTHS = [
  {
    asset: 'USD',
    category: 'forex',
    sign: '$',
    description: 'US Dollars',
    name: 'pUSD',
    subclass: 'MultiCollateralPynth',
  },
];

export default {
  1: MAINNET_PYNTHS,
  3: ROPSTEN_PYNTHS,
  4: RINKEBY_PYNTHS,
  5: GOERLI_PYNTHS,
  42: KOVAN_PYNTHS,
  137: POLYGON_PYNTHS,
  80001: MUMBAI_PYNTHS,
};
