export default [
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_resolver', type: 'address' },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'name',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'destination',
        type: 'address',
      },
    ],
    name: 'CacheUpdated',
    type: 'event',
    signature: '0x88a93678a3692f6789d9546fc621bf7234b101ddb7d4fe479455112831b8aa68',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'pynth',
        type: 'address',
      },
    ],
    name: 'PynthAdded',
    type: 'event',
    signature: '0xe82414a85733a2b51473d0ab66a73f2af64f044531104dc04ca01db8c9c5f5cf',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'pynth',
        type: 'address',
      },
    ],
    name: 'PynthRemoved',
    type: 'event',
    signature: '0x1f2a4e9868db18b9d103e44efacb2690000d9d78bd600bf5f24757e13f0f891b',
  },
  {
    constant: true,
    inputs: [],
    name: 'CONTRACT_NAME',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x614d08f8',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'contract IPynth',
        name: 'pynth',
        type: 'address',
      },
    ],
    name: 'addPynth',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x156b4ff6',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'contract IPynth[]',
        name: 'pynthsToAdd',
        type: 'address[]',
      },
    ],
    name: 'addPynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x5543dadc',
  },
  {
    constant: true,
    inputs: [],
    name: 'anyPynthOrPERIRateIsInvalid',
    outputs: [{ internalType: 'bool', name: 'anyRateInvalid', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf5adc4f5',
  },
  {
    constant: true,
    inputs: [],
    name: 'availableCurrencyKeys',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x72cb051f',
  },
  {
    constant: true,
    inputs: [],
    name: 'availablePynthCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xd99947de',
  },
  {
    constant: true,
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'availablePynths',
    outputs: [{ internalType: 'contract IPynth', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9df95f9f',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'burnPynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x095314a8',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'address',
        name: 'burnForAddress',
        type: 'address',
      },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'burnPynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xe71c452f',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'from', type: 'address' }],
    name: 'burnPynthsToTarget',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x56c25f82',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'address',
        name: 'burnForAddress',
        type: 'address',
      },
      { internalType: 'address', name: 'from', type: 'address' },
    ],
    name: 'burnPynthsToTargetOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x4669106a',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'canBurnPynths',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2ae78fdb',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'collateral',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xa5fdc5de',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '_issuer', type: 'address' }],
    name: 'collateralisationRatio',
    outputs: [{ internalType: 'uint256', name: 'cratio', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xa311c7c2',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '_issuer', type: 'address' }],
    name: 'collateralisationRatioAndAnyRatesInvalid',
    outputs: [
      { internalType: 'uint256', name: 'cratio', type: 'uint256' },
      { internalType: 'bool', name: 'anyRateIsInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xae3bbbbb',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: '_issuer', type: 'address' },
      { internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' },
    ],
    name: 'debtBalanceOf',
    outputs: [{ internalType: 'uint256', name: 'debtBalance', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xd37c4d8b',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
    ],
    name: 'getPynths',
    outputs: [
      {
        internalType: 'contract IPynth[]',
        name: '',
        type: 'address[]',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x1db63a33',
  },
  {
    constant: true,
    inputs: [],
    name: 'isResolverCached',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2af64bd3',
  },
  {
    constant: true,
    inputs: [],
    name: 'issuanceRatio',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xb410a034',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: 'from', type: 'address' }],
    name: 'issueMaxPynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xf0617e5b',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'address',
        name: 'issueForAddress',
        type: 'address',
      },
      { internalType: 'address', name: 'from', type: 'address' },
    ],
    name: 'issueMaxPynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x30662ab9',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'issuePynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xba921223',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'address',
        name: 'issueForAddress',
        type: 'address',
      },
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'issuePynthsOnBehalf',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xdaa01015',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'lastIssueEvent',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xdd3d2b2e',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'uint256', name: 'pusdAmount', type: 'uint256' },
      { internalType: 'address', name: 'liquidator', type: 'address' },
    ],
    name: 'liquidateDelinquentAccount',
    outputs: [
      {
        internalType: 'uint256',
        name: 'totalRedeemed',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'amountToLiquidate',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xa63c4df4',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '_issuer', type: 'address' }],
    name: 'maxIssuablePynths',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x55182ccb',
  },
  {
    constant: true,
    inputs: [],
    name: 'minimumStakeTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x242df9e1',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: false,
    inputs: [],
    name: 'rebuildCache',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x74185360',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '_issuer', type: 'address' }],
    name: 'remainingIssuablePynths',
    outputs: [
      { internalType: 'uint256', name: 'maxIssuable', type: 'uint256' },
      {
        internalType: 'uint256',
        name: 'alreadyIssued',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'totalSystemDebt',
        type: 'uint256',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x3b09280a',
  },
  {
    constant: false,
    inputs: [{ internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' }],
    name: 'removePynth',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x4c29b0af',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
    ],
    name: 'removePynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x6017c458',
  },
  {
    constant: true,
    inputs: [],
    name: 'resolver',
    outputs: [
      {
        internalType: 'contract AddressResolver',
        name: '',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x04f3bcec',
  },
  {
    constant: true,
    inputs: [],
    name: 'resolverAddressesRequired',
    outputs: [
      {
        internalType: 'bytes32[]',
        name: 'addresses',
        type: 'bytes32[]',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x899ffef4',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'pynths',
    outputs: [{ internalType: 'contract IPynth', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x57ad4663',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'pynthsByAddress',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc9a2f3ad',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' },
      {
        internalType: 'bool',
        name: 'excludeEtherCollateral',
        type: 'bool',
      },
    ],
    name: 'totalIssuedPynths',
    outputs: [{ internalType: 'uint256', name: 'totalIssued', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf023e8db',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
    ],
    name: 'transferablePeriFinanceAndAnyRateIsInvalid',
    outputs: [
      {
        internalType: 'uint256',
        name: 'transferable',
        type: 'uint256',
      },
      { internalType: 'bool', name: 'anyRateIsInvalid', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8d542eb3',
  },
];
