export default [
  {
    inputs: [{ internalType: 'address', name: 'resolver', type: 'address' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    constant: true,
    inputs: [],
    name: 'addressResolverProxy',
    outputs: [
      {
        internalType: 'contract IAddressResolver',
        name: '',
        type: 'address',
      },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xd18ab376',
  },
  {
    constant: true,
    inputs: [],
    name: 'frozenPynths',
    outputs: [{ internalType: 'bytes32[]', name: '', type: 'bytes32[]' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xeade6d2d',
  },
  {
    constant: true,
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'pynthsBalances',
    outputs: [
      { internalType: 'bytes32[]', name: '', type: 'bytes32[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xa827bf48',
  },
  {
    constant: true,
    inputs: [],
    name: 'pynthsRates',
    outputs: [
      { internalType: 'bytes32[]', name: '', type: 'bytes32[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x27fe55a6',
  },
  {
    constant: true,
    inputs: [],
    name: 'pynthsTotalSupplies',
    outputs: [
      { internalType: 'bytes32[]', name: '', type: 'bytes32[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x492dbcdd',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' },
    ],
    name: 'totalPynthsInKey',
    outputs: [{ internalType: 'uint256', name: 'total', type: 'uint256' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x0120be33',
  },
];
