export default [
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'constructor',
    signature: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'section',
        type: 'bytes32',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'canSuspend',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'canResume',
        type: 'bool',
      },
    ],
    name: 'AccessControlUpdated',
    type: 'event',
    signature: '0x95bad30f8fe717e4a02906d7b05a6f90698c7135cd053e5b6d5239146b4c40d1',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'ExchangeResumed',
    type: 'event',
    signature: '0x07966fe79d35c7abf1f3b2ad9970ea24cae0f11406e283e848e3e6608ae3c214',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'ExchangeSuspended',
    type: 'event',
    signature: '0x078773069a9216cdb6acaa7b184785f12f62048c7ce8b7ede1bad6785de16b22',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'IssuanceResumed',
    type: 'event',
    signature: '0x0f1a80395faba9a11017f830db5f90ad6525a1621dbfb2cbc2b6679ba5716837',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'IssuanceSuspended',
    type: 'event',
    signature: '0xee8bf45d6e3141aa521ae4f0d05dfefe0327a3f23a9fbae6a64680458b34ebb8',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'oldOwner',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerChanged',
    type: 'event',
    signature: '0xb532073b38c83145e3e5135377a08bf9aab55bc0fd7c1179cd4fb995d2a5159c',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnerNominated',
    type: 'event',
    signature: '0x906a1c6bd7e3091ea86693dd029a831c19049ce77f1dce2ce0bab1cacbabce22',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'PynthExchangeResumed',
    type: 'event',
    signature: '0xc6cc5bbf2969f74a5166d0bad983455bf7a65b6372af7260400f9b3b04338090',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'PynthExchangeSuspended',
    type: 'event',
    signature: '0x0af76046e49b0af43f6e092983123f6fb3a25f63bd7096c1bb89649a75a9a494',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'PynthResumed',
    type: 'event',
    signature: '0xddc88fc179cf33f24e5569dd8635c3cd44864e66a1b359bdd9d95e50d94a0d39',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'currencyKey',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'PynthSuspended',
    type: 'event',
    signature: '0xfd3feff79fa642f72408a90c33c6b2ae245bd7077eec45d2502714178e692c86',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'SystemResumed',
    type: 'event',
    signature: '0xb392a95118344e8edff8eff56183afb4bb0240310c406a0fc1217d2755c66d8f',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'reason',
        type: 'uint256',
      },
    ],
    name: 'SystemSuspended',
    type: 'event',
    signature: '0x86b7ed06c3a2c3763514d475ced33f9ac8b1bb8f028ded18de0100b7678f3c4f',
  },
  {
    constant: true,
    inputs: [],
    name: 'SECTION_EXCHANGE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf1616207',
  },
  {
    constant: true,
    inputs: [],
    name: 'SECTION_ISSUANCE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x4abdb44d',
  },
  {
    constant: true,
    inputs: [],
    name: 'SECTION_PYNTH',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x1635b0ce',
  },
  {
    constant: true,
    inputs: [],
    name: 'SECTION_PYNTH_EXCHANGE',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x387da909',
  },
  {
    constant: true,
    inputs: [],
    name: 'SECTION_SYSTEM',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x12bde514',
  },
  {
    constant: true,
    inputs: [],
    name: 'SUSPENSION_REASON_UPGRADE',
    outputs: [{ internalType: 'uint248', name: '', type: 'uint248' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x9f8a95ba',
  },
  {
    constant: false,
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x79ba5097',
  },
  {
    constant: true,
    inputs: [
      { internalType: 'bytes32', name: '', type: 'bytes32' },
      { internalType: 'address', name: '', type: 'address' },
    ],
    name: 'accessControl',
    outputs: [
      { internalType: 'bool', name: 'canSuspend', type: 'bool' },
      { internalType: 'bool', name: 'canResume', type: 'bool' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x20f2bf00',
  },
  {
    constant: true,
    inputs: [],
    name: 'exchangeSuspension',
    outputs: [
      { internalType: 'bool', name: 'suspended', type: 'bool' },
      { internalType: 'uint248', name: 'reason', type: 'uint248' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xf8b4b084',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32[]', name: 'pynths', type: 'bytes32[]' }],
    name: 'getPynthExchangeSuspensions',
    outputs: [
      {
        internalType: 'bool[]',
        name: 'exchangeSuspensions',
        type: 'bool[]',
      },
      { internalType: 'uint256[]', name: 'reasons', type: 'uint256[]' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x0d2d7c28',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32[]', name: 'pynths', type: 'bytes32[]' }],
    name: 'getPynthSuspensions',
    outputs: [
      { internalType: 'bool[]', name: 'suspensions', type: 'bool[]' },
      { internalType: 'uint256[]', name: 'reasons', type: 'uint256[]' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0xc09290bb',
  },
  {
    constant: true,
    inputs: [],
    name: 'isSystemUpgrading',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2e8d0b9e',
  },
  {
    constant: true,
    inputs: [],
    name: 'issuanceSuspension',
    outputs: [
      { internalType: 'bool', name: 'suspended', type: 'bool' },
      { internalType: 'uint248', name: 'reason', type: 'uint248' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2366245e',
  },
  {
    constant: false,
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'nominateNewOwner',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1627540c',
  },
  {
    constant: true,
    inputs: [],
    name: 'nominatedOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x53a47bb7',
  },
  {
    constant: true,
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8da5cb5b',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'pynthExchangeSuspension',
    outputs: [
      { internalType: 'bool', name: 'suspended', type: 'bool' },
      { internalType: 'uint248', name: 'reason', type: 'uint248' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x4ef4a643',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    name: 'pynthSuspension',
    outputs: [
      { internalType: 'bool', name: 'suspended', type: 'bool' },
      { internalType: 'uint248', name: 'reason', type: 'uint248' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x8c38729d',
  },
  {
    constant: true,
    inputs: [],
    name: 'requireExchangeActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x7118d431',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32',
        name: 'sourceCurrencyKey',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: 'destinationCurrencyKey',
        type: 'bytes32',
      },
    ],
    name: 'requireExchangeBetweenPynthsAllowed',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2cb28bd8',
  },
  {
    constant: true,
    inputs: [],
    name: 'requireIssuanceActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x7c312541',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' }],
    name: 'requirePynthActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x1d7e7789',
  },
  {
    constant: true,
    inputs: [{ internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' }],
    name: 'requirePynthExchangeActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x89bb3dfa',
  },
  {
    constant: true,
    inputs: [
      {
        internalType: 'bytes32',
        name: 'sourceCurrencyKey',
        type: 'bytes32',
      },
      {
        internalType: 'bytes32',
        name: 'destinationCurrencyKey',
        type: 'bytes32',
      },
    ],
    name: 'requirePynthsActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x3cb4d443',
  },
  {
    constant: true,
    inputs: [],
    name: 'requireSystemActive',
    outputs: [],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x086dabd1',
  },
  {
    constant: false,
    inputs: [],
    name: 'resumeExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xf405f65a',
  },
  {
    constant: false,
    inputs: [],
    name: 'resumeIssuance',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x67a280b2',
  },
  {
    constant: false,
    inputs: [{ internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' }],
    name: 'resumePynth',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xd7f2c385',
  },
  {
    constant: false,
    inputs: [{ internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' }],
    name: 'resumePynthExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x08d10e62',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
    ],
    name: 'resumePynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x2e94d93d',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
    ],
    name: 'resumePynthsExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x14acc95f',
  },
  {
    constant: false,
    inputs: [],
    name: 'resumeSystem',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x157c51d3',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'reason', type: 'uint256' }],
    name: 'suspendExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x1588e817',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'reason', type: 'uint256' }],
    name: 'suspendIssuance',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x396e258e',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' },
      { internalType: 'uint256', name: 'reason', type: 'uint256' },
    ],
    name: 'suspendPynth',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x631070fc',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'bytes32', name: 'currencyKey', type: 'bytes32' },
      { internalType: 'uint256', name: 'reason', type: 'uint256' },
    ],
    name: 'suspendPynthExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x754a4641',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
      { internalType: 'uint256', name: 'reason', type: 'uint256' },
    ],
    name: 'suspendPynths',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x87743c36',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'currencyKeys',
        type: 'bytes32[]',
      },
      { internalType: 'uint256', name: 'reason', type: 'uint256' },
    ],
    name: 'suspendPynthsExchange',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xad135a16',
  },
  {
    constant: false,
    inputs: [{ internalType: 'uint256', name: 'reason', type: 'uint256' }],
    name: 'suspendSystem',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0xe470df58',
  },
  {
    constant: true,
    inputs: [],
    name: 'systemSuspension',
    outputs: [
      { internalType: 'bool', name: 'suspended', type: 'bool' },
      { internalType: 'uint248', name: 'reason', type: 'uint248' },
    ],
    payable: false,
    stateMutability: 'view',
    type: 'function',
    signature: '0x2dd8afdb',
  },
  {
    constant: false,
    inputs: [
      { internalType: 'bytes32', name: 'section', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
      { internalType: 'bool', name: 'canSuspend', type: 'bool' },
      { internalType: 'bool', name: 'canResume', type: 'bool' },
    ],
    name: 'updateAccessControl',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x48bf1971',
  },
  {
    constant: false,
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'sections',
        type: 'bytes32[]',
      },
      {
        internalType: 'address[]',
        name: 'accounts',
        type: 'address[]',
      },
      { internalType: 'bool[]', name: 'canSuspends', type: 'bool[]' },
      { internalType: 'bool[]', name: 'canResumes', type: 'bool[]' },
    ],
    name: 'updateAccessControls',
    outputs: [],
    payable: false,
    stateMutability: 'nonpayable',
    type: 'function',
    signature: '0x517d60c6',
  },
];
